### PR TITLE
Get data from RDS

### PR DESCRIPTION
**Pull request by kulikov98**
Kindly ask you to come back for review tomorrow, 10/11. Overtime work didn't let me do the home task on the weekend.

Thanks for your patience!

### CODE REVIEW

**Comment by byslavik** [comment]
@kulikov98  Please ping me when it will be ready for review :)

**Comment by RemZiQ** [comment]
Hello @kulikov98. Please provide some description and link for triggering lambda. Currently, I see only 4.1 is done, in 4.2 required to provide the link. Please ping me if you will update description. For now, it's only 1 point for this task

**Comment by DevandScorp** [comment]
@kulikov98 waiting for you

**Comment by kulikov98** [comment]
**I finally made it!** 😄 
endpoints:
  GET - https://d5q2m0ntch.execute-api.us-east-1.amazonaws.com/dev/products
  GET - https://d5q2m0ntch.execute-api.us-east-1.amazonaws.com/dev/products/{id}
  POST - https://d5q2m0ntch.execute-api.us-east-1.amazonaws.com/dev/products

**Comment by DevandScorp** [comment]
@kulikov98 can you provide your frontend app with all required integrations?

**Comment by kulikov98** [comment]
Not yet, didn't have time for that. I'll make FE integration later.

**Pull request merged**
